### ISSUE TITLE
Fails to build in npm environment

### ISSUE THREAD

**Issue by emlynmac** [xlsdg/react-simplemde-v1#1]
(function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)

ERROR in ../~/react-simplemde-v1/lib/index.jsx
    Module parse failed: /Volumes/Data/emlyn/Documents/Code/BoltonTek/zenxmed-cms/node_modules/react-simplemde-v1/lib/index.jsx Unexpected token (97:6)
    You may need an appropriate loader to handle this file type.

**Comment by xlsdg** [comment]
webpack2:

```js
{
  test: /\.jsx$/,
  loader: 'babel-loader',
  include: [
    resolve('src'),
    resolve('test'),
    resolve('node_modules/react-simplemde-v1')
  ]
}
```
